# paasta-cubrid-service 설정 파일 내용
name: on-cubrid                               # 서비스 배포이름(필수)

releases:
- name: "on-demand-cubrid"                    #서비스 릴리즈 이름(필수)
  version: "latest"                           #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1                               # canary 인스턴스 수(필수)
  canary_watch_time: 30000-180000           # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 6                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-180000           # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: cubrid                              #작업 이름(필수): Cubrid 서버
  azs: [z1]
  instances: 1           # job 인스턴스 수(필수)
  vm_type: small
  persistent_disk_type: 10GB               # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: default           # cloud config 에 정의한 network 이름
  jobs:
  - name: cubrid
    release: "on-demand-cubrid"
properties:
  port: 1524
  database_name: 'egov_platform_database'
  password: 'pch1234'
